#---
#apiVersion: cert-manager.io/v1
#kind: Certificate
#metadata:
#  name: dexterslab-tls
#  namespace: envoy-gateway-system
#spec:
#  secretName: dexterslab-tls
#  issuerRef:
#    name: letsencrypt
#    kind: ClusterIssuer
#  dnsNames:
#    - "dexterslab.cc"
#    - "*.dexterslab.cc"
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: primary-gateway
  namespace: envoy-gateway-system
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: primary-gateway
  namespace: envoy-gateway-system
spec:
  gatewayClassName: primary-gateway
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
#    - name: https
#      protocol: HTTPS
#      port: 443
#      tls:
#        mode: Terminate
#        certificateRefs:
#          - kind: Secret
#            name: dexterslab-tls
#      allowedRoutes:
#        namespaces:
#          from: All
