rootDomain: ""
gateway:
  name: ""
  namespace: ""

jellyfin:
  image:
    repository: jellyfin/jellyfin
    pullPolicy: IfNotPresent
    tag: "latest"
  workingDir: /home/jellyfin
  timezone: Etc/UTC
  replicaCount: 1
  resources: {}
  service:
    type: ClusterIP
    port: 80
    appPort: 8096
  healthcheck:
    livenessProbe:
      httpGet:
        path: /health
        port: 8096
    readinessProbe:
      httpGet:
        path: /health
        port: 8096
  securityContext: {}
  volumes: []
  volumeMounts: []

jellyseerr:
  image:
    repository: fallenbagel/jellyseerr
    pullPolicy: IfNotPresent
    tag: "latest"
  workingDir: /home/jellyseerr
  timezone: Etc/UTC
  replicaCount: 1
  resources: {}
  service:
    type: ClusterIP
    port: 80
    appPort: 5055
  healthcheck:
    livenessProbe:
      exec:
        command:
          - "nc"
          - "-z"
          - "localhost"
          - "5055"
    readinessProbe:
      exec:
        command:
          - "nc"
          - "-z"
          - "localhost"
          - "5055"
  securityContext: {}
  volumes: []
  volumeMounts: []

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

nodeSelector: {}

tolerations: []

affinity: {}
