---
apiVersion: v1
kind: Namespace
metadata:
  name: torrent-clients
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: torrent-client-credentials
  namespace: torrent-clients
spec:
  encryptedData:
    PASSWORD: AgCv5gtVaFqEP9pT92CKWD1Rs/EhHG/3Wpf3VnJKsH8I4VNuHO7UPOxM9xeIC3Q2UmNn36Elid+1dxXuE5HABD0YWrvTQMMALxHpJeaYIMueDhQartfmNp1lHhXcufmDp+86lm9t+X+JXp6vBT+HwCSp+N7EHX8msBqmulox36rXfeTgFnQVEJRQZdZM7T7atu4536m+tyCbqVVSCFI66l49qBNzaQMhueyqUYTI/xpr7/DfiWDnV/CBU5UmvEH6pTzywB5r6NHxDiLd562UFgvdpl+ldypQcbKpmR9cbPv1j8YiRgcv77X/DXjj/YvVVvrL//7sgdrXpt4EfWPCWbcVBs+V1yc78ffCgET7ehOZjQY0L9rCbCNETy6rsXSdtS4CVMbzOfPxkXZkUkK71TLKRaJ6nXyNe7VPq6QrF/q/4jLS7q/r1UDX+3t547XThEICCXIE8d+aMCgY4tJPDEAmR1zC2ahn1vJt1xsEK7/sRUU/ycxF4lsrKyQcUchmudr5tmEpesE3byL+Lpdve838opyu7pNyYa6OyIPr4wYPQ3DBdbwuwCjnFzaygrnNyGAcz5knt1ZWazh6IPr2a5cE4b5a4LAyx6NcgNMtzxhOEKmahrG6FQCGEQeN2PmLsP9GnvjukHaw9v6yJtauo7iKQrock2gf/9GBvZKZOoqlyJU/FBr06FFo/bDf+ccPLl1wCBDct0j/vfAvzF+JlCbYTW3z64W63xep00wiJncQpQ==
    SABNZBD_API_KEY: AgCs/GhVg5fX9szix9eDmR321DofUfd6f8Ootc6R1kxs22KP1ksnW3V3mRN+dGEqDESiQUm5MpFU4lvKeoQ1qCsmZIMrj9VT7zdj8zRMyTOmfc+fs5XYuHuuWtCCec/vV/Rs1E2yC9Ata8ZxQY7OsP9pNQcNZNcWZbEysaALs0/S+O70CJvNpba/PJU0XCELvfl/B/Hcl2uF75+pS7fVPpi8cSMlFOiIYI6hXPLp1ON+eM9oDoqs2xGfZ+AgAi9BL4Cc3U5zRF22EOZaRaVUrWHDe/MR1t9v7doinz69koj97GYbHmqZ7r6PO8v6AsjzDft4cUL9//7OxubMvERKZJyaaY62pA8SY1fDnK44ORtmVK1Xb+wq1vHl4isry7XBGbKoVpEBaxmgD8pPoLiwsEeHZ1zAKPYaYZpRqLl5UG//WqjUE0cWVNi7llvvpnlexgDdzMni8vcGMe18OktxH1GF0xXofrh3mQnoWvyHgITejW790lGC7O9HaNjnRkLDINLtnxmX2z+xNoqUxB9dMKXVVpQSpcgQNqENrweryikcu0zjo+mtec4+flImadtv/5xbCw483WCXQdTE4vCq1IKc3drWWJnNHmBiy5HK17Me1KGerm0d18hcfuvtr5G1/oL+btfGuu+sVwvFR4Zyix6CoZHOdQWpaLv9r/khGC6F710mqTXlOeW1wdxr6B/ZT54Pun2zPLHuEB7tghnMHzijcwLw+w==
    USERNAME: AgC03R0pd0UMdvOumRmLKe9LEW51wnQ4T64ieT9V652Iw71WVQ7DApQquqKvysA+05sAsZmf/2UrG8yZbmBtImEvu5GIwh6a4qGK4TjoBLnqPL/aUgYV00MptnnhomOdB6Cr1cPnqnA9eFOMS6hxwHy5BoeyO8f3BvaVl1XKdmPXp6J/QfQ2pbGl24Sda+439Bf17Rq9juqK2cUFBjqDM0kyrY/DVffMtZ3ngEALHQ7/H4I2qqQy/Hf33E2eMf2378W6JvyhKggVOAJA5eKPg1jxG0krtMzENLROKjO5HE/ru49uAW5fiS2ut53ET1eGcJ7rDDTwVfpgGkhp4omsNVX+qBcDw2d+8r8ZA6tmcf/DY15xvZ/lzVtDRomAS86e72HrMnjuXziX2qsSkIwnNtGGRe+HFNfFdv9EjLy7wLDZxRjHD9H3+Rh6a6vIkBGJSkgZETp5uurfu3ol0Cyz+EQ08aWvJcIyUdsbPGETTi7oFR/YK5NSB0T8YvbFGrr5Pgkc/hy3XwWLt9owN8d/WtoilbiWk1QwfvtPSsB6g785FzO2LlcpNrREe8BHZmNMZq+rK5eB5pqUJ77PI76bHfzRW+/QE3aTLQmdWl/NQzG+l00EOPLIfIgC2+HZzi1OlNaeWb1y0P5sZ8UEA5Yr5XZH3TznTIAaGDwolKGSFU/wIvqxFulfKonrsyms9MTdOij5DImHq4WicN2g+ew=
  template:
    metadata:
      creationTimestamp: null
      name: torrent-client-credentials
      namespace: torrent-clients