---
apiVersion: v1
kind: Namespace
metadata:
  name: torrent-clients
---
apiVersion: v1
kind: Secret
metadata:
  name: torrent-client-credentials
  namespace: torrent-clients
data:
  NZB_PASSWORD: "{{ NZB_PASSWORD | b64encode}}"
  NZB_USERNAME: "{{ NZB_USERNAME | b64encode}}"
  PASSWORD: "{{ PASSWORD | b64encode}}"
  SABNZBD_API_KEY: "{{ SABNZBD_API_KEY | b64encode}}"
  USERNAME: "{{ USERNAME | b64encode}}"
