---
apiVersion: v1
kind: Namespace
metadata:
  name: keel
---
apiVersion: v1
kind: Secret
metadata:
  name: keel-credentials
  namespace: keel
data:
  BASIC_AUTH_USER: "{{ KEEL_USERNAME | b64encode }}"
  BASIC_AUTH_PASSWORD: "{{ KEEL_PASSWORD | b64encode }}"
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: keel
  namespace: keel
spec:
  parentRefs:
    - name: primary-gateway
      namespace: envoy-gateway-system
  hostnames:
    - "keel.dexterslab.cc"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: keel
          port: 80
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /