apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseerr
  labels:
    app.kubernetes.io/app: jellyseerr
    {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.jellyseerr.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/app: jellyseerr
      {{- include "jellyfin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        app.kubernetes.io/app: jellyseerr
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/app: jellyseerr
        {{- include "jellyfin.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "jellyfin.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-jellyseerr
          {{- with .Values.jellyseerr.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.jellyseerr.image.repository }}:{{ .Values.jellyseerr.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.jellyseerr.image.pullPolicy }}
          env:
            - name: TZ
              value: "{{ .Values.jellyseerr.timezone }}"
          ports:
            - name: http
              containerPort: {{ .Values.jellyseerr.service.appPort }}
              protocol: TCP
          {{- with .Values.jellyseerr.healthcheck.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.jellyseerr.healthcheck.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.jellyseerr.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          {{- with .Values.jellyseerr.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.jellyseerr.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
