---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudflare
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secrets
  namespace: cloudflare
spec:
  encryptedData:
    CLOUDFLARE_API_TOKEN: AgB5YOi4a24eoh9Ev9uD1VxkYlEc4RAa3QarUaMsptirHgMipT5fd5SXfHw+MzrRFfTs2APvaDUYhlVMvTaMmCWF/k5RRhQg9zI8ZSXnzpUTwArmOu8aszA4nXPokOFWqg2ZOC77ga/S9PJ3ZYvT24AI4K7wiAqM9SEQIvWL1xWZdcR9vyMvyo05O2hzpJtPJEjzGTJ/O7y7touE8YQRnCPTTthAmFabufxji5FUySwARG04SpW6sdFPJRuytaFv9v5HuXeznwTHErkHiQU1W9A+DBV/m3O6opaGAnf512XTKPtUIsE/Cnhv+4zLBvWQPQWttlEtH+w03Oz/u0Uf18Kl/HLjzx0BSbv7toLA4hPOlAMQ8dRQufL8BUAo95fMClpuld4zRo3IVCqSR5fsspstDKdGUlMa/BW6Ikc39OygsxJInWs6gWc1yVPMK7uEqk8d5jJ90rS+c0urRAdiHRCfTi2McqICNA1W4hJVLmpcQMo3vukH86U71fdTRLlH7S3A9cg6nqO0lQWbcg1gLhjLpfhdYPbdGLin2WwdyrepsaoOMk7QzS+G9HdGwhO05VHrGarDjq+jRTpYVgl2hUgA/1Jw6NOAWt9B9AxGGlC89n5tximo/rvK8yZ88RgL8h52wjaVOkZG1tX+deEe5+TJX8GH5i7swrA3ChcecQYbd1H09O0/63Mo+yPRl+mK9u4W70K80g+vkWLaKW6irUSnmUJ32TR8TUZ4Av5gQAAzi81af5s4p4p6FsU=
    CLOUDFLARE_TUNNEL_TOKEN: AgCJZHfKy+9v130GDdQC6jOhkLmaJnivLxCVa9n0u2gKzhQSwThnCQLhCahR2hNXeUDfHSbIietbvp1jp5KUHesbegJYYx0h+5HR1CfBn+wTVkg8WFzNf6Pe5MFtVHCGThuYb9KuK+eA4ye9RrmcLJbgKSZrdP63U3f4dMoEN42gqYZHunQdh3ZFIneIoTBRMbVG7y3UHyjy38olf6DioWinQXwFB/jMn3CaNW7UkJ1uSBAHAtf62zJaSDldv72fmdG2IeASGSrF7p9y6r41kF1vZ3NKtj+dY1H50s6VFw+yNyNc0e+EcspycXp3kQ9yYpLQBSU9gMr1+o5v2qzwLy7v4W2Dhl1XwIbP6obOJhKYsHKRqCykN+B8Y0LDTqxFuuSt9Krifly6iraB7mAshJgUzCtwjt5eoYjYtXTBnmzuYdwZtmH1F0R56yMCPl7AEUCavSQTF/2SIWJhxDfJNWbh5SAgKyXT+3wJzpY1+sjAGERbT41BiucjFmYBzBjuLTax3nDqd+ssH70Pebo+u1INdjsXbKNxcYd9FqLqwTia1N+00BnpJoBk+4dTviVaPQvhBgjvMIRFP8kA+Uf2bn8YaWZeoaQk/bTcPC1n/b+C0hYQ4uLSfQu9nEGA8eDtAbSnGlLmiLSaaVVkgJE7Pdi4tVjzIRFUh98GLVkFz27e887Y+1WcG0xX91DF5oj8BWe/n48rvALg5ro9ulQZEuYoi8y7VrUcoJ22lKmsmGw+4jBbEi62bpQdVQLSjjH4z2t28f3dhskoyLP6HdRzWW0eFA1crhFIT9Gr0YEE+uWEw6H7B5iLdi1i4NOIp/TX4SyEJmifP6l5ZTM++Gl/OOay81Wi1RJ5W50oNCwcrlwG4Mt4TKQAxe4yhZXNHddpdZUMjAWfKGTo7MND99TIcqE1PzH234SiUvzq1N5+ZA9kOq8wDaBuQ9Q020s=
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-secrets
      namespace: cloudflare