---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudflare
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-secrets
  namespace: cloudflare
data:
    CLOUDFLARE_API_TOKEN: "{{ CLOUDFLARE_API_TOKEN | b64encode }}"
    CLOUDFLARE_TUNNEL_TOKEN: "{{ CLOUDFLARE_TUNNEL_TOKEN | b64encode }}"
