- name: Install services
  block:
    - name: Add haproxy chart repo
      kubernetes.core.helm_repository:
        name: haproxytech
        repo_url: "https://haproxytech.github.io/helm-charts"
      delegate_to: localhost
    - name: Install haproxy ingress
      kubernetes.core.helm:
        context: "archlinux"
        name: "haproxy-unified-gateway"
        chart_ref: "haproxytech/haproxy-unified-gateway"
        release_namespace: haproxy
        values_files:
          - "../services/gateway/haproxy/values.yaml"
      delegate_to: localhost
    - name: Install gateway resources
      kubernetes.core.k8s:
        context: "archlinux"
        src: "{{ item }}"
        state: present
      delegate_to: localhost
      loop:
        - "https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.5.0/experimental-install.yaml"
        - "../services/gateway/haproxy/config.yaml"
    - name: Load cloudflare env
      import_tasks: "common/read_env.yml"
      vars:
        path: "../services/cloudflare/.envrc"
    - name: Configure cloudflare tunnel
      kubernetes.core.k8s:
        context: "archlinux"
        template:
          - path: "../services/cloudflare/config.yaml"
        state: present
      delegate_to: localhost
    - name: Install cloudflare tunnel
      kubernetes.core.helm:
        context: "archlinux"
        name: "cloudflare-tunnel"
        chart_ref: "../charts/cloudflare-tunnel"
        release_namespace: cloudflare
        values_files:
          - "../services/cloudflare/values.yaml"
      delegate_to: localhost