{{- if not .Values.cloudflare.externalSecret.enabled }}
# This credentials secret allows cloudflared to authenticate itself
# to the Cloudflare infrastructure.
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflare-tunnel.fullname" . }}
  labels:
    {{- include "cloudflare-tunnel.labels" . | nindent 4 }}
stringData:
  tunnelToken: {{ .Values.cloudflare.tunnel_token }}
{{- end }}