---
- name: Homelab
  hosts: homelab
  vars:
    real_interfaces:
      - enp0s31f6
      - tailscale0
  tasks:
    - name: Ping
      ping:
#    - name: Setup k0s
#      import_tasks: "tasks/1.k0s.yml"
    - name: Setup services
      import_tasks: "tasks/2.services.yml"
    - name: Setup apps
      import_tasks: "tasks/3.apps.yml"
