apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "torrent-clients.fullname" . }}-sabnzbd-ini-template
  labels:
    {{- include "torrent-clients.labels" . | nindent 4 }}
data:
  sabnzbd.ini: |-
    {{- .Files.Get "sabnzbd.ini" | nindent 4 }}