global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "localhost:9090" ]
  - job_name: 'docker'
    static_configs:
      - targets: [ "host.docker.internal:9333" ]
  - job_name: "traefik"
    static_configs:
      - targets: [ "traefik:8080" ]
  - job_name: "nodeexporter"
    static_configs:
      - targets: [ 'nodeexporter:9100' ]
  - job_name: 'cadvisor'
    static_configs:
      - targets: [ 'cadvisor:8080' ]
  - job_name: "watchtower"
    metrics_path: "/v1/metrics"
    bearer_token: "{{ watchtower_api_token }}"
    static_configs:
      - targets: [ "watchtower:8080" ]
